### ISSUE TITLE
Refactoring and tests

### ISSUE THREAD

**Issue by naumenkogs** [Finhaven/ValidatedToken#3]
- [x] refactor dependencies
- [x] general cleanup
- [x] remove weird inherited functions we don't really need
- [x] simple validator test
- [x] reference token test
- [ ] truffle overload issue

**Comment by expede** [comment]
@naumenkogs yep, that sounds about right 👍 Would you like me to look at the WIP so far? I might not be seeing it on the `refactor` branch 🤔

**Comment by expede** [comment]
Closed by #4
